name: CI

on:
  push:
    branches:
      - master

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: build project
#       run: |
#         npm install
#         npm run build
#         ls -a
#     - name: Copy folder content recursively to remote
#       uses: garygrossgarten/github-action-scp@release
#       with:
#         local: build
#         remote: ../../var/www/swiper-app
#         host: ${{ secrets.HOST }}
#         username: githubcicd
#         password: ${{ secrets.PASSWORD }}
